backend:
  name: github
  branch: main
  repo: vcser/vcser.github.io
  base_url: https://decap.vicentecser.xyz

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://vcser.github.io/
locale: "es"

collections:
- name: blog
  label: "Posts"
  label_singular: "Post"
  folder: blog
  identifier_field: title
  format: "yaml-frontmatter"
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string, required: false }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Author"
      name: "authors"
      widget: "select"
      default: "vcser"
      options: ["vcser"]
    - label: "Enable comments"
      name: "enableComments"
      widget: "boolean"
      default: true